config/routes.rb
Tabletop::Application.routes.draw do
  devise_for :users
  root to: 'lobbies#index'
  get "lobbies/chat"

  resources :game_definitions

end

app/models/game_definition.rb
class GameDefinition
  include Mongoid::Document

  field :name, type: String
  field :description, type: String
  field :author, type: String
  field :version, type: String
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :login, :presence => true, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :login
  end
end

app/controllers/game_definitions_controller.rb
class GameDefinitionsController < ApplicationController

  def index
    @game_definitions = GameDefinition.all
  end

  def new
    @game_definition = GameDefinition.new
  end

  def create
    @game_definition = GameDefinition.new(permissible_params)

    if @game_definition.save
      redirect_to @game_definition, notice: 'Game definition was successfully created.'
    else
      render action: 'new'
    end
  end

  def edit
    @game_definition = GameDefinition.find(params[:id])
  end

  def update
    @game_definition = GameDefinition.find(params[:id])
    if @game_definition.update_attributes(permissible_params)
      redirect_to @game_definition, notice: 'Game definition was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def show
    @game_definition = GameDefinition.find(params[:id])
  end

  def destroy
    @game_definition = GameDefinition.find(params[:id])
    @game_definition.destroy
    redirect_to game_definitions_path
  end

  private

  def permissible_params
    params.require(:game_definition).permit(:name, :description, :author, :version)
  end
end

app/controllers/lobbies_controller.rb
class LobbiesController < ApplicationController
  include Tubesock::Hijack

  before_filter :authenticate_user!

  def chat
    hijack do |tubesock|

      redis_thread = Thread.new do
        # Needs its own redis connection to pub
        # and sub at the same time
        Redis.new.subscribe "lobby" do |on|
          on.message do |channel, json|
            data = JSON.parse(json)
            message = "[#{data['time']}] #{data['user']} said: #{data['message']}"
            tubesock.send_data message
          end
        end
      end

      tubesock.onmessage do |msg|
        Redis.new.publish "lobby", { user: current_user.login, time: Time.now, message: msg }.to_json
      end

      tubesock.onclose do
        # stop listening when client leaves
        redis_thread.kill
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_definitions_helper.rb
module GameDefinitionsHelper
end

app/helpers/lobbies_helper.rb
module LobbiesHelper
end

app/views/game_definitions/edit.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="nav nav-tabs nav-stacked">
      <li><%= link_to 'Show', game_definition_path(@game_definition) %></li>
      <li><%= link_to 'Back', game_definitions_path %></li>
    </ul>
  </div>
  <div class="col-md-9" role="main">
    <div class="panel panel-default">
      <div class="panel-body">
        Edit Game Definition
      </div>
      <div class="panel-footer">
        <%= form_for @game_definition, url: { action: 'create' }, :html => { :role => "form" } do |f| %>
          <!-- <p> -->
          <!--   <%#= render 'shared/error_messages', object: f.object %> -->
          <!-- </p> -->
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, :class => 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :author %>
            <%= f.text_field :author, :class => 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :version %>
            <%= f.text_field :version, :maxlength => 20 , :class => 'form-control'%>
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, :class => "form-control" %>
          </div>

          <div class="form-group">
            <%= f.submit nil, :class => 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/game_definitions/index.html.erb
<div class ="page-header">
  <h1>Game Definitions</h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Author</th>
      <th>Version</th>
      <th>Actions</th>
    </tr>
  </thead>
  <% @game_definitions.each do | game_definition | %>
    <tr>
      <td><%= game_definition.name %></td>
      <td><%= game_definition.author %></td>
      <td><%= game_definition.version %></td>
      <td>
        <%= link_to content_tag(:i, "", class: "icon-pencil icon-white") + " Edit",
          edit_game_definition_path(game_definition), :method => :get, :class => 'btn btn-margin btn-success' %>

        <%= link_to content_tag(:i, "", class: "icon-trash icon-white") + " Destroy",
        game_definition_path(game_definition), :method => :delete,
        :data => { :confirm => 'Are you sure you want to delete this game definition?' },
        :class => 'btn btn-danger btn-margin' %>
      </td>
    </tr>
  <% end %>
</table>

<%= link_to "New Game Definition", new_game_definition_path, :class => 'btn btn-primary' %>

app/views/game_definitions/new.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    New Game Definition
  </div>
  <div class="panel-footer">
    <%= form_for @game_definition, url: { action: 'create' }, :html => { :role => "form" } do |f| %>
      <!-- <p> -->
      <!--   <%#= render 'shared/error_messages', object: f.object %> -->
      <!-- </p> -->
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, :class => 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :author %>
        <%= f.text_field :author, :class => 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :version %>
        <%= f.text_field :version, :maxlength => 20 , :class => 'form-control'%>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, :class => "form-control" %>
      </div>

      <div class="form-group">
        <%= f.submit nil, :class => 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/game_definitions/show.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="nav nav-tabs nav-stacked">
      <li><%= link_to 'Edit', edit_game_definition_path(@game_definition) %></li>
      <li><%= link_to 'Back', game_definitions_path %></li>
    </ul>
  </div>
  <div class="col-md-9" role="main">
    <div class="panel panel-default">
      <div class="panel-body">
        Game Definition: <%= @game_definition.name %>
      </div>
      <div class="panel-footer">

        <ul class="list-unstyled">
          <li class="form-group">
            <label class="col-lg-2 control-label">Name</label>
            <span class="form-control-static"><%= @game_definition.name %></span>
          </li>

          <li class="form-group">
            <label class="col-lg-2 control-label">Author</label>
            <span class="form-control-static"><%= @game_definition.author %></span>
          </li>

          <li class="form-group">
            <label class="col-lg-2 control-label">Version</label>
            <span class="form-control-static"><%= @game_definition.version %></span>
          </li>

          <li class="form-group">
            <label class="col-lg-2 control-label">Description</label>
            <span class="form-control-static"><%= @game_definition.description %></span>
          </li>
        </ul>

      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tabletop</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Tabletop</a>
    </div>
    <div class="navbar-collapse collapse">
      <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#lobby">Lobby</a></li>
          <li><%= link_to "Game Definitions", game_definitions_path, :class => 'navbar-link' %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
        </ul>
        <p class="navbar-text navbar-right">Signed in as  <strong><%= current_user.login %></strong></p>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
          <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
        </ul>
      <% end %>
    </div>
  </div>
</div>

<div class="container">

  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% end %>

  <% if alert %>
    <p class="alert"><%= alert %></p>
  <% end %>

  <%= yield %>
</div>

</body>
</html>

app/views/lobbies/index.html.erb
<div class="row">

  <form role="form" class="chat">
    <div class="form-group">
      <input class="form-control" placeholder="send message" autofocus>
    </div>
  </form>

  <p>
    <pre id="output"></pre>
  </p>
</div>